### ISSUE TITLE
Which version is stable ?

### ISSUE THREAD

**Issue by LW-archlinux** [artix-linux/opensysusers#14]
I'm looking at updating the archl8inux aur package for this, but am unclear which version I should update to .

The last relase is 0.4.8 , but there are several newer versions tagged like 0.4.8.1 , 0.4.9 , 0.5 & 0.5.1 .
Which should be considered the latest stable version ?

**Comment by konimex** [comment]
The latest release is 0.5.1 since we just `git tag`ged it and don't post it in GitHub anymore (this repo now serves as mirror).

See https://gitea.artixlinux.org/artix/opensysusers/releases for upstream links.

**Comment by LW-archlinux** [comment]
Thank you for making clear where upstream files can be found.

On the gitea releases page, version 0.4.9 is clearly marked as stable and the only version that shows that mark.

are 0.5 & 0.5.1 considered development versions ?
If not, you may want to move the 'stable' mark to reflect this.

**Comment by konimex** [comment]
0.5.1 is considered stable since we have it in our official repos. https://gitea.artixlinux.org/packagesO/opensysusers
