### ISSUE TITLE
/bin/sysusers: line 105: [: ==: unary operator expected

### ISSUE THREAD

**Issue by LW-archlinux** [artix-linux/opensysusers#5]
opensysusers 0.3.1

Interesting package, I'll upload it to archlinux AUR soon.
Have you considered submitting it to upstream openrc ?

    [ ${cline:0:1} == "#" ] && continue

I think bash expects 2 strings, adding double quotes around `${cline:0:1}` made the message go away.

**Comment by cromerc** [comment]
Damn laptop touchpad, hit close by accident. Anyway, thank you very much for the support. I had mentioned the project in the openrc irc channel a while back but nobody spoke up about any interest in the project. The project is designed to be init agnostic so it should work for openrc, s6, runit, or whatever else.

Also, just pushed a fix to your issue: ec289ccae3752b1c18d316e1ac0ec9d8de10c430

**Comment by LW-archlinux** [comment]
Nice to hear it's designed to work with multiple systems.
arch linux package has been uploaded to AUR, https://aur.archlinux.org/packages/opensysusers
It focuses on openrc for now,  but should be easy to adjust for other inits.

The fix works, closing.
