### ISSUE TITLE
Init script should not be part of package

### ISSUE THREAD

**Issue by Tank-Missile** [artix-linux/opensysusers#6]
All openrc init scripts, as far as I'm aware, are separated into their own packages, except for this one. For consistency, it should be separated into its own optional package.

**Comment by cromerc** [comment]
Incorrect, the ones that are separated are ones that are not included in the upstream package. For example apache upstream does not include an openrc script, so it gets a separate package. In the case of opensysusers, the openrc script is supplied officially by the opensysusers project, so it does not go into a separate package.

**Comment by udeved** [comment]
The same is true for opentmpfiles.
any runit or s6 implementation would have to supply scripts for opensysusers and opentmpfiles
