### ISSUE TITLE
man is borked in makefile

### ISSUE THREAD

**Issue by udeved** [artix-linux/opensysusers#8]
The makefiles are borked.
I fixed the install calls, but the man compile needs a look.

I can fix the man too so it at least tries to compile them.

```
make[1]: Warnung: Kein Jobserver verfügbar: -j1 wird gesetzt. Fügen Sie der Ursprungsregel
„+“ hinzu.


```

**Comment by udeved** [comment]
Will push a patch to make man compile. all fine now.

**Comment by cromerc** [comment]
What does the message say? I don't speak German. ;)

**Comment by udeved** [comment]
make[1]: Warnung: Kein Jobserver verfügbar: -j1 wird gesetzt. Fügen Sie der Ursprungsregel
„+“ hinzu.

"warning: no jobserver available: .j1 will be set. Add "+" to the source rules"

Its what it says.

**Comment by udeved** [comment]
Btw, should I push some makefile improvements which fix some PREFIX inconsistencies?

**Comment by cromerc** [comment]
Yes please. I trust your work.

**Comment by udeved** [comment]
PREFIX depending vars should use $(PREFIX)/$var at initialization. ;)

**Comment by udeved** [comment]
https://github.com/artix-linux/opensysusers/commit/397e1eb5f88f6e2c21765e1c40a86ae86bbdaa21
